export const campaigns = [
  {
    id: "reeldeal-ugc-facecam",
    rank: 1,
    name: "ReelDeal It - UGC Facecam",
    brand: "ReelDeal Support",
    rate: 1.0,
    img: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "10 000 $",
    maxPerVideo: "500 $",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Crée une vidéo facecam authentique montrant comment tu utilises ReelDeal pour gagner de l'argent en tant que créateur. Montre ton tableau de bord, tes gains, et explique le processus avec tes propres mots.",
    brief: [
      "Filme en format vertical 9:16, minimum 1080p",
      "Montre ton visage à l'écran pendant au moins 50 % de la vidéo",
      "Mentionne « ReelDeal » à l'oral et ajoute le lien dans ta bio",
      "Durée de la vidéo entre 20 et 60 secondes",
      "Aucune promesse de gains trompeuse",
    ],
  },
  {
    id: "game-launch-hype",
    rank: 2,
    name: "Game Launch Hype",
    brand: "Riot Games",
    rate: 0.8,
    img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=800&fit=crop",
    category: "Gaming",
    budget: "25 000 $",
    maxPerVideo: "400 $",
    platforms: ["TikTok", "YouTube Shorts"],
    description: "Fais monter la hype autour du lancement de la nouvelle saison avec des clips de gameplay, des réactions ou des tier-lists. Montre un vrai enthousiasme et tes meilleures actions.",
    brief: [
      "Utilise des extraits de gameplay officiels ou tes propres enregistrements",
      "Indique la date de sortie dans ta légende",
      "Garde de l'énergie — montage rapide, sons tendance",
      "Durée de la vidéo entre 15 et 45 secondes",
    ],
  },
  {
    id: "streetwear-season",
    rank: 3,
    name: "Streetwear Season",
    brand: "Supreme",
    rate: 0.65,
    img: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&h=800&fit=crop",
    category: "Mode",
    budget: "18 000 $",
    maxPerVideo: "350 $",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Stylise le nouveau drop à ta façon. Fit checks, transitions d'outfits et hauls streetwear — montre comment la collection s'intègre à tes looks du quotidien.",
    brief: [
      "Mets en avant au moins une pièce du drop en cours",
      "Format transition d'outfit ou fit check de préférence",
      "Lumière naturelle, décors urbains encouragés",
      "Tague le compte de la marque dans ta publication",
    ],
  },
  {
    id: "glow-up-routine",
    rank: 4,
    name: "Glow Up Routine",
    brand: "Glossier",
    rate: 0.55,
    img: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&h=800&fit=crop",
    category: "Beauté",
    budget: "15 000 $",
    maxPerVideo: "300 $",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Partage ta routine skincare du matin ou du soir avec les produits. Le contenu authentique de type get-ready-with-me performe le mieux.",
    brief: [
      "Format GRWM ou routine",
      "Montre l'application du produit à l'écran",
      "Les premières impressions honnêtes sont les bienvenues",
      "Durée de la vidéo entre 30 et 60 secondes",
    ],
  },
  {
    id: "study-smarter",
    rank: 5,
    name: "Study Smarter",
    brand: "Diane AI",
    rate: 0.5,
    img: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=800&fit=crop",
    category: "Éducation",
    budget: "12 000 $",
    maxPerVideo: "250 $",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Montre aux étudiants comment tu utilises l'IA pour réviser plus vite et avoir de meilleures notes. Les formats astuces d'étude et avant/après fonctionnent très bien.",
    brief: [
      "Montre l'application à l'écran au moins une fois",
      "Cible les étudiants (lycée / université)",
      "Format astuces d'étude ou storytelling",
      "Ajoute le lien de téléchargement dans ta bio",
    ],
  },
  {
    id: "build-in-public",
    rank: 6,
    name: "Build In Public",
    brand: "Blink.new",
    rate: 0.45,
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "9 000 $",
    maxPerVideo: "250 $",
    platforms: ["TikTok", "YouTube Shorts"],
    description: "Construis un site web ou une app en direct à l'écran avec la plateforme et partage le résultat. Parfait pour les audiences tech, business et side-hustle.",
    brief: [
      "Enregistre ton écran pendant la création",
      "Montre le résultat final à la fin",
      "Précise que c'est gratuit pour commencer",
      "Durée de la vidéo entre 20 et 60 secondes",
    ],
  },
  {
    id: "morning-fuel",
    rank: 7,
    name: "Morning Fuel",
    brand: "Alani Nu",
    rate: 0.4,
    img: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&h=800&fit=crop",
    category: "Fitness",
    budget: "8 000 $",
    maxPerVideo: "200 $",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Intègre la boisson énergisante dans ta routine matinale, ta séance de sport ou ton contenu day-in-the-life. Une intégration lifestyle plutôt qu'une pub agressive.",
    brief: [
      "Montre clairement la canette au moins une fois",
      "Format salle de sport, routine matinale ou DITL",
      "Reste sur du lifestyle, pas une lecture de pub",
    ],
  },
  {
    id: "sound-on",
    rank: 8,
    name: "Sound On",
    brand: "JBL",
    rate: 0.35,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "7 500 $",
    maxPerVideo: "200 $",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Déballe, teste et donne ton avis sur les derniers casques. Tests audio, setups de bureau esthétiques et avis honnêtes correspondent à cette campagne.",
    brief: [
      "Format unboxing ou review",
      "Montre le produit en utilisation",
      "Les avis honnêtes sont encouragés",
      "Durée de la vidéo entre 20 et 60 secondes",
    ],
  },
];

export const getCampaign = (id) => campaigns.find((c) => c.id === id);