export const campaigns = [
  {
    id: "reeldeal-ugc-facecam",
    rank: 1,
    name: "ReelDeal It - UGC Facecam",
    brand: "ReelDeal Support",
    rate: 1.0,
    img: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "$10,000",
    maxPerVideo: "$500",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Create an authentic facecam video showing how you use ReelDeal to earn money as a creator. Show your dashboard, your earnings, and explain the process in your own words.",
    brief: [
      "Film in vertical 9:16 format, minimum 1080p",
      "Show your face on camera for at least 50% of the video",
      "Mention 'ReelDeal' verbally and add the link in your bio",
      "Video length between 20 and 60 seconds",
      "No misleading earnings claims",
    ],
  },
  {
    id: "game-launch-hype",
    rank: 2,
    name: "Game Launch Hype",
    brand: "Riot Games",
    rate: 0.8,
    img: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=800&fit=crop",
    category: "Gaming",
    budget: "$25,000",
    maxPerVideo: "$400",
    platforms: ["TikTok", "YouTube Shorts"],
    description: "Hype up the launch of the new season with gameplay clips, reactions, or tier-list content. Show genuine excitement and your best plays.",
    brief: [
      "Use official gameplay footage or your own recordings",
      "Include the launch date in your caption",
      "Keep it energetic — fast cuts, trending sounds",
      "Video length between 15 and 45 seconds",
    ],
  },
  {
    id: "streetwear-season",
    rank: 3,
    name: "Streetwear Season",
    brand: "Supreme",
    rate: 0.65,
    img: "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&h=800&fit=crop",
    category: "Fashion",
    budget: "$18,000",
    maxPerVideo: "$350",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Style the new drop your way. Fit checks, outfit transitions, and streetwear hauls — show how the collection fits into your daily looks.",
    brief: [
      "Feature at least one item from the current drop",
      "Outfit transition or fit-check format preferred",
      "Natural lighting, urban settings encouraged",
      "Tag the brand account in your post",
    ],
  },
  {
    id: "glow-up-routine",
    rank: 4,
    name: "Glow Up Routine",
    brand: "Glossier",
    rate: 0.55,
    img: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&h=800&fit=crop",
    category: "Beauty",
    budget: "$15,000",
    maxPerVideo: "$300",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Share your morning or evening skincare routine featuring the products. Authentic, get-ready-with-me style content performs best.",
    brief: [
      "GRWM or routine format",
      "Show product application on camera",
      "Honest first impressions welcome",
      "Video length between 30 and 60 seconds",
    ],
  },
  {
    id: "study-smarter",
    rank: 5,
    name: "Study Smarter",
    brand: "Diane AI",
    rate: 0.5,
    img: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=800&fit=crop",
    category: "Education",
    budget: "$12,000",
    maxPerVideo: "$250",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Show students how you use AI to study faster and get better grades. Study-tips and before/after formats work great for this campaign.",
    brief: [
      "Show the app on screen at least once",
      "Target students (high school / university)",
      "Study-tips or storytelling format",
      "Add the download link in your bio",
    ],
  },
  {
    id: "build-in-public",
    rank: 6,
    name: "Build In Public",
    brand: "Blink.new",
    rate: 0.45,
    img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "$9,000",
    maxPerVideo: "$250",
    platforms: ["TikTok", "YouTube Shorts"],
    description: "Build a website or app live on camera using the platform and share the result. Perfect for tech, business, and side-hustle audiences.",
    brief: [
      "Screen-record the building process",
      "Show the final result at the end",
      "Mention that it's free to start",
      "Video length between 20 and 60 seconds",
    ],
  },
  {
    id: "morning-fuel",
    rank: 7,
    name: "Morning Fuel",
    brand: "Alani Nu",
    rate: 0.4,
    img: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&h=800&fit=crop",
    category: "Fitness",
    budget: "$8,000",
    maxPerVideo: "$200",
    platforms: ["TikTok", "Instagram Reels"],
    description: "Feature the energy drink in your morning routine, gym session, or day-in-the-life content. Lifestyle integration over hard selling.",
    brief: [
      "Show the can clearly at least once",
      "Gym, morning routine, or DITL format",
      "Keep it lifestyle-focused, not an ad read",
    ],
  },
  {
    id: "sound-on",
    rank: 8,
    name: "Sound On",
    brand: "JBL",
    rate: 0.35,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop",
    category: "Tech",
    budget: "$7,500",
    maxPerVideo: "$200",
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
    description: "Unbox, test, and review the latest headphones. Sound tests, aesthetic desk setups, and honest reviews all fit this campaign.",
    brief: [
      "Unboxing or review format",
      "Show the product in use",
      "Honest opinions encouraged",
      "Video length between 20 and 60 seconds",
    ],
  },
];

export const getCampaign = (id) => campaigns.find((c) => c.id === id);